### ISSUE TITLE
Links não funcionando

### ISSUE THREAD

**Issue by CleytonBonamigo** [cerebrobr/apresentacoes#24]
Recentemente, analisei os links que são da Intercon, da Imasters, e os mesmos são direcionados para o próprio site da Intercon, porém, sem o conteúdo do vídeo.

Os assuntos, mais especificamente, estão na Área de Marketing Digital.

**Comment by thulioph** [comment]
@CleytonBonamigo obrigado pelo retorno, mas poderia ajudar a gente nessa? Se você puder listar aqui os links que estão quebrados a gente pode corrigir, ou se você preferir poderia corrigi-los e nos mandar um PR. O que acha? :smile:

**Comment by CleytonBonamigo** [comment]
Eu adoraria ajudar, porém, infelizmente não consegui achar os links funcionando para o vídeos.
Os links são esses:

### Web analytics/Big Data
* [Data Visualization – Teoria, Técnicas e práticas](http://intercon.imasters.com.br/conteudo/data-visualization-teoria-tecnicas-e-praticas/)
* [Data-Driven Marketing / Digital Analytics Trends](http://intercon.imasters.com.br/conteudo/data-driven-marketing-digital-analytics-trends-futuro-das-metricas-otimizacao-e-inteligencia-de-negocios/)
* [Explorando a API do Google Analytics](http://intercon.imasters.com.br/conteudo/explorando-a-api-do-google-analytics/)
* [Segmentação e personalização – Behavioral Targeting e Retargeting na prática](http://intercon.imasters.com.br/conteudo/segmentacao-e-personalizacao-behavioral-targeting-e-retargeting-na-pratica/)
* [Social Mining para métricas – Extraindo dados direto da fonte](http://intercon.imasters.com.br/conteudo/social-mining-para-metricas-extraindo-dados-direto-da-fonte/)
* [Testes A/B – Experimentando conteúdo e otimizando conversões](http://intercon.imasters.com.br/conteudo/testes-ab-experimentando-conteudo-e-otimizando-conversoes/)
* [Web Analytics Hacks – Implementação avançada de métricas, customizações e truques](http://intercon.imasters.com.br/conteudo/web-analytics-hacks-implementacao-avancada-de-metricas-customizacoes-e-truques/)

### SEO/PPC
* [Análise Multi-canais e Modelos de atribuição de campanhas na prática](http://intercon.imasters.com.br/conteudo/analise-multi-canais-e-modelos-de-atribuicao-de-campanhas-na-pratica/)
* [Search Marketing Optimization na prática](http://intercon.imasters.com.br/conteudo/search-marketing-optimization-na-pratica/)

**Comment by nicholasess** [comment]
Faz um PR com os links ativos e links quebrado, é uma boa, pois quem achar os links corretos, é só mandar o PR com as informações corretas.
O que achm?
@cerebrobr/colaboradores @cerebrobr/editores

**Comment by pedropolisenso** [comment]
Uma boa forma de fazer a galera contribuir e de motivar a alguns a fazerem
seu primeiro PR.
Em 11/02/2015 06:07, "Nicholas Eduardo" <notifications@github.com> escreveu:

**Comment by vitorbritto** [comment]
:+1:

**Comment by niltoncms** [comment]
Consegui os links pras apresentações, com exceção de uma, lá no slideshare (os links dos vídeos no iMasters ainda estão redirecionando pra home do InterCon 2014). Mas como esse repo é só de apresentações fica a dúvida: é preferível abrir uma seção lá no [repo de slides](https://github.com/cerebrobr/slides) ou contribuir nesse mesmo, porém com uma observação e linkando pra essa issue?! 
Prefiro a segunda opção, porque quando o link voltar a gente atualiza.

**Comment by fdaciuk** [comment]
Acho que aqui mesmo @niltoncms.. até porque não são slides né? xD
E seria legal deixar um aviso que os links direcionam para a home do InterCon, para alguém lembrar de atualizar estiver ok :smile:

**Comment by niltoncms** [comment]
O foda é que os links são os slides das apresentações, @fdaciuk, e justamente por isso a sugestão de deixar uma observação e linkar aqui pra issue, onde a discussão toda tá concentrada. Valeu pela dica :)) Vou aguardar mais gente se manifestar aqui, mas por enquanto tô contigo em dar PR aqui mesmo!
